### PR TITLE
run pip and black in virtual enviroment

### PR DESCRIPTION
**Pull request by tarukumar**
This is to run pip and black code in virtual env.

This will avoid running with root access while docker image is getting build

### CODE REVIEW

**Comment by tarukumar** [comment]
@rickstaa Could you check if above changes are good and accepted

**Comment by rickstaa** [comment]
Tests passed (see https://github.com/rickstaa/action-test-repo/pull/72/) ✔️

**Comment by rickstaa** [comment]
@tarukumar Thanks a lot for making this action more safe! 🚀

**Comment by rickstaa** [comment]
@tarukumar, your pull request was not working (see https://github.com/rickstaa/action-black/runs/8202368384?check_suite_focus=true). I think my test was incomplete. I had to make the following changes https://github.com/rickstaa/action-black/pull/15. Could you please double-check if the action is now working?

**Pull request merged**
